/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  
  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: '新功能',
      items: [
        'new-feature/lock-screen',
        'new-feature/desktop-editting',
        'new-feature/aigc-theme',
        'new-feature/shake-phone',
        'new-feature/movie-camera',
        'new-feature/dynamic-photo',
        'new-feature/xiaoyi-wakeup',
        'new-feature/xiaoyi-calendar',
        'new-feature/xiaoyi-picture',
        'new-feature/touch-share',
        'new-feature/air-transfer',
        'new-feature/intelligent-control-key',
        'new-feature/intelligent-notification',
        'new-feature/agenda-share',
      ],
    },
    {
      type: 'category',
      label: '快速上手',
      items: [
        'quick-start/gesture-navigation',
        'quick-start/lock-task',
        'quick-start/volume',
        'quick-start/lock-screen-tool',
        'quick-start/lock-screen',
        'quick-start/card-to-desktop',
        'quick-start/control-center',
        'quick-start/broadcast-center',
        'quick-start/notification-center',
        'quick-start/task-information',
        'quick-start/finger-joint-screenshot',
        'quick-start/screen-recording',
        'quick-start/split-screen',
        'quick-start/float-window',
        'quick-start/transfer-station',
        'quick-start/data-clone',
        'quick-start/changlian',

      ],
    },
    {
      type: 'category',
      label: '智慧体验',
      items: [
        'ai/screen-recognition',
        'ai/finger-joint-circle-selection',
        'ai/answer-devices-question',
        'ai/xiaoyi-memory',
        'ai/memo',
        'ai/scan-id-card',
        'ai/extract-image-subject',
        'ai/extract-image-text',
        'ai/recognize-music',
        'ai/one-click-translation',
        'ai/xiaoyi-subtitle',
        'ai/xiaoyi-search',
        'ai/smart-payment',
        'ai/smart-scan-qr-code',
        'ai/remote-gesture-screenshot',
        'ai/remote-gesture-scroll-screen',

      ],
    },
    {
      type: 'category',
      label: '纯净安全',
      items: [
        'security/privacy-light',
        'security/manage-app-permission',
        'security/app-lock',
        'security/hide-private-content',
        'security/file-cabinet',
        'security/3d-facial-recognition',
        'security/one-click-close-sensitive-permission',
        'security/share-encrypt-file',
        'security/auto-fill-in-password',
        'security/search-lost-device',
        'security/external-storage',
        'security/satellite-communication',

      ],
    },
    {
      type: 'category',
      label: '精彩影像',
      items: [
        'camera/zoom-ring',
        'camera/one-hand-camera-operation',
        'camera/adjust-camera-setting',
        'camera/one-click-shooting',
        'camera/fictitious-background',
        'camera/ai-enhancement',
        'camera/ai-elimination',
        'camera/ai-expansion',
        'camera/photo-graffiti',
        'camera/multi-image-comparison',
        'camera/automatic-classification',
        'camera/time-album',

      ],
    },
  ],
   
};

module.exports = sidebars;
