/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  
  // But you can create a sidebar manually
  
  phoneSidebar: [
    {
      type: 'category',
      label: '新功能',
      items: [
        'new-feature/lock-screen',
        'new-feature/desktop-editting',
        'new-feature/aigc-theme',
        'new-feature/shake-phone',
        'new-feature/movie-camera',
        'new-feature/dynamic-photo',
        'new-feature/xiaoyi-wakeup',
        'new-feature/xiaoyi-calendar',
        'new-feature/xiaoyi-picture',
        'new-feature/touch-share',
        'new-feature/air-transfer',
        'new-feature/intelligent-control-key',
        'new-feature/intelligent-notification',
        'new-feature/agenda-share',
      ],
    },
    {
      type: 'category',
      label: '快速上手',
      items: [
        'quick-start/gesture-navigation',
        'quick-start/lock-task',
        'quick-start/volume',
        'quick-start/lock-screen-tool',
        'quick-start/lock-screen',
        'quick-start/card-to-desktop',
        'quick-start/control-center',
        'quick-start/broadcast-center',
        'quick-start/notification-center',
        'quick-start/task-information',
        'quick-start/finger-joint-screenshot',
        'quick-start/screen-recording',
        'quick-start/split-screen',
        'quick-start/float-window',
        'quick-start/transfer-station',
        'quick-start/data-clone',
        'quick-start/changlian',

      ],
    },
    {
      type: 'category',
      label: '智慧体验',
      items: [
        'ai/screen-recognition',
        'ai/finger-joint-circle-selection',
        'ai/answer-devices-question',
        'ai/xiaoyi-memory',
        'ai/memo',
        'ai/scan-id-card',
        'ai/extract-image-subject',
        'ai/extract-image-text',
        'ai/recognize-music',
        'ai/one-click-translation',
        'ai/xiaoyi-subtitle',
        'ai/xiaoyi-search',
        'ai/smart-payment',
        'ai/smart-scan-qr-code',
        'ai/remote-gesture-screenshot',
        'ai/remote-gesture-scroll-screen',

      ],
    },
    {
      type: 'category',
      label: '纯净安全',
      items: [
        'security/privacy-light',
        'security/manage-app-permission',
        'security/app-lock',
        'security/hide-private-content',
        'security/file-cabinet',
        'security/3d-facial-recognition',
        'security/one-click-close-sensitive-permission',
        'security/share-encrypt-file',
        'security/auto-fill-in-password',
        'security/search-lost-device',
        'security/external-storage',
        'security/satellite-communication',

      ],
    },
    {
      type: 'category',
      label: '精彩影像',
      items: [
        'camera/zoom-ring',
        'camera/one-hand-camera-operation',
        'camera/adjust-camera-setting',
        'camera/one-click-shooting',
        'camera/fictitious-background',
        'camera/ai-enhancement',
        'camera/ai-elimination',
        'camera/ai-expansion',
        'camera/photo-graffiti',
        'camera/multi-image-comparison',
        'camera/automatic-classification',
        'camera/time-album',

      ],
    },

    {
      type: 'category',
      label: '个性设置',
      items: [
        'setting/weather-theme',
        'setting/raindrop-theme',
        'setting/stack-cards',
        'setting/large-folder',
        'setting/adjust-font',
        'setting/dark-mode',
        'setting/switch-input-method',
        'setting/screen-usage-time',
        'setting/minor-mode',
        'setting/care-mode',

      ],
    },

    {
      type: 'category',
      label: '全场景',
      items: [
        'full-scene/huawei-share',
        'full-scene/super-device',
        'full-scene/seamless-connection',
        'full-scene/cross-device-copy-paste',
        'full-scene/cross-device-photo',
        'full-scene/connect-phone-tablet',
        'full-scene/cross-device-drag-drop-file',
        'full-scene/wireless-screen-mirroring',
        'full-scene/touch-it',
        'full-scene/super-desktop',
        'full-scene/huawei-hicar',
      ],
    },
  ],

  pcSidebar: [
    
    {
      type: 'category',
      label: '新机上手',
      items: [
        'quick-start-pc/harmonyos',
        'quick-start-pc/app-center',
        'quick-start-pc/control-center',
        'quick-start-pc/desktop-card',
        'quick-start-pc/data-clone',
        'quick-start-pc/screenshot',
        'quick-start-pc/screen-recording',
        'quick-start-pc/split-screen',
        'quick-start-pc/notice',
        'quick-start-pc/start',
      ],
    },

    {
      type: 'category',
      label: '全场景',
      items: [
        'full-scene-pc/super-device',
        'full-scene-pc/mouse-keyboard-sharing',
        'full-scene-pc/switch-keyboard-mouse',
        'full-scene-pc/cross-device-image-acquisition',
        'full-scene-pc/huawei-share',
        'full-scene-pc/multi-screen-collaboration',
        'full-scene-pc/one-touch-connection',
        'full-scene-pc/task-continuation',
        'full-scene-pc/copy-and-paste',
        'full-scene-pc/communication-sharing',
        'full-scene-pc/wireless-screen-mirroring',
        'full-scene-pc/broadcasting-center',
        
      ],
    },
    
    {
      type: 'category',
      label: '智慧体验',
      items: [
        'ai-pc/xiaoyi-search',
        'ai-pc/xiaoyi-wakeup',
        'ai-pc/xiaoyi-assistant',
        'ai-pc/xiaoyi-calendar',
        'ai-pc/xiaoyi-image',
        'ai-pc/xiaoyi-meeting',
        'ai-pc/xiaoyi-subtitle',
        'ai-pc/xiaoyi-noise-reduction',
        'ai-pc/xiaoyi-ktv',
        
      ],
    },

    {
      type: 'category',
      label: '常用手势',
      items: [
        'gesture/knuckle',
        'gesture/double-finger-opening-closing',
        'gesture/double-finger-sliding',
        'gesture/double-finger-swipe',
        'gesture/three-finger-sliding-upwards',
        'gesture/three-finger-slideup-pause',
        'gesture/right-click',
        

        
      ],
    },

    {
      type: 'category',
      label: '快捷键',
      items: [
        'shortcut-key/open-startup-window',
        'shortcut-key/close-current-application',
        'shortcut-key/hotkey-mode',
        'shortcut-key/xiaoyi-search',
        'shortcut-key/regional-screenshot',
        'shortcut-key/shortcut-key-prompt-panel',
        'shortcut-key/show-desktop',
        'shortcut-key/lock-screen',
        'shortcut-key/control-center',
        'shortcut-key/view-all-running-applications',
        'shortcut-key/view-files-on-computer',
        'shortcut-key/view-all-installed-applications',
        'shortcut-key/view-notice',

      
      ],
    },

    {
      type: 'category',
      label: '高效办公',
      items: [
        'work/memo',
        'work/intelligent-organization',
        'work/todo-list',
        'work/manage-schedule',
        'work/share-agenda',
        'work/extract-image-subject',
        'work/extract-image-text',
        'work/jiasaw-puzzle',
        'work/search-file',
      ],
    },

    {
      type: 'category',
      label: '纯净安全',
      items: [
        'security-pc/privacy-light',
        'security-pc/security-status',
        'security-pc/disable-camera-permission',
        'security-pc/fingerprint-unlock',
        'security-pc/autofill-password',
        'security-pc/document-cabinet',
        'security-pc/encrypt-file',
        'security-pc/lock-memo',
        'security-pc/hide-privacy-file',
        'security-pc/external-storage-backup',
        'security-pc/find-device',
       
      ],
    },

    {
      type: 'category',
      label: '个性设置',
      items: [
        'setting-pc/change-wallpaper',
        'setting-pc/show-battery-percentage',
        'setting-pc/change-mouse-style',
        'setting-pc/change-font-display-size',
        'setting-pc/screen-auto-turn-off-duration',
        'setting-pc/dark-mode',
        'setting-pc/intelligent-charging',
       
      ],
    },
  ],
   
};

module.exports = sidebars;
